name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: add extra programs for tests
      run: |
        sudo apt-get update
        sudo apt-get install emacs emacs-nox gdb screen tcsh zsh
    - name: configure
      run: ./configure --enable-logging
    - name: make
      run: make
    - name: make tests
      run: make tests
    - name: make check
      run: ./test/autotest.py --retry-once
